### ISSUE TITLE
Getting crash reports Caused by java.lang.NullPointerException

### ISSUE THREAD

**Issue by yaro-melnychuk** [DeepARSDK/deepar-flutter-plugin#85]
Getting reports from Crashlytics on the released app about NullPointerException

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.setMethodCallHandler(io.flutter.plugin.common.MethodChannel$MethodCallHandler)' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5586)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5619)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2410)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
       at `com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)`
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.setMethodCallHandler(io.flutter.plugin.common.MethodChannel$MethodCallHandler)' on a null object reference
       at com.deepar.ai.DeepArPlugin.onDetachedFromEngine(DeepArPlugin.java:368)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:270)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:280)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:288)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:121)
       at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:434)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:708)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:762)
       at android.app.Activity.performDestroy(Activity.java:8820)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1472)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5573)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5619)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2410)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
```

looks like the error comes from **onDetachedFromEngine(DeepArPlugin.java:368)**
it appears on devices with Android 10+ mostly in the background state
![image](https://github.com/DeepARSDK/deepar-flutter-plugin/assets/85098704/77cf57f2-4c48-4286-b2ce-4ba31d5e1f32)

**Comment by skol101** [comment]
Hello @wilson-christian , would you look into it?

**Comment by bjmcallister** [comment]
Also, getting this issue.
